type Timezone = { name: string; value: string };

const genericTimezones: Timezone[] = [
  { name: 'UTC-12:00', value: 'Etc/GMT+12' },
  { name: 'UTC-11:00', value: 'Etc/GMT+11' },
  { name: 'UTC-10:00', value: 'Etc/GMT+10' },
  { name: 'UTC-09:00', value: 'Etc/GMT+9' },
  { name: 'UTC-08:00', value: 'Etc/GMT+8' },
  { name: 'UTC-07:00', value: 'Etc/GMT+7' },
  { name: 'UTC-06:00', value: 'Etc/GMT+6' },
  { name: 'UTC-05:00', value: 'Etc/GMT+5' },
  { name: 'UTC-04:00', value: 'Etc/GMT+4' },
  { name: 'UTC-03:00', value: 'Etc/GMT+3' },
  { name: 'UTC-02:00', value: 'Etc/GMT+2' },
  { name: 'UTC-01:00', value: 'Etc/GMT+1' },
  { name: 'UTC±00:00', value: 'Etc/GMT' },
  { name: 'UTC+01:00', value: 'Etc/GMT-1' },
  { name: 'UTC+02:00', value: 'Etc/GMT-2' },
  { name: 'UTC+03:00', value: 'Etc/GMT-3' },
  { name: 'UTC+04:00', value: 'Etc/GMT-4' },
  { name: 'UTC+05:00', value: 'Etc/GMT-5' },
  { name: 'UTC+06:00', value: 'Etc/GMT-6' },
  { name: 'UTC+07:00', value: 'Etc/GMT-7' },
  { name: 'UTC+08:00', value: 'Etc/GMT-8' },
  { name: 'UTC+09:00', value: 'Etc/GMT-9' },
  { name: 'UTC+10:00', value: 'Etc/GMT-10' },
  { name: 'UTC+11:00', value: 'Etc/GMT-11' },
  { name: 'UTC+12:00', value: 'Etc/GMT-12' },
  { name: 'UTC+13:00', value: 'Etc/GMT-13' },
  { name: 'UTC+14:00', value: 'Etc/GMT-14' },
];
const timezones: Timezone[] = [
  { name: '🌍 UTC (Default)', value: 'UTC' },
  { name: '🇧🇷 Brazil', value: 'America/Sao_Paulo' },
  { name: '🇺🇸 USA (New York)', value: 'America/New_York' },
  { name: '🇨🇦 Canada (Toronto)', value: 'America/Toronto' },
  { name: '🇮🇹 Italy', value: 'Europe/Rome' },
  { name: '🇦🇷 Argentina', value: 'America/Argentina/Buenos_Aires' },
  { name: '🇨🇱 Chile', value: 'America/Santiago' },
  { name: '🇲🇽 Mexico', value: 'America/Mexico_City' },
  { name: '🇨🇴 Colombia', value: 'America/Bogota' },
  { name: '🇺🇸 USA (Chicago)', value: 'America/Chicago' },
  { name: '🇺🇸 USA (Denver)', value: 'America/Denver' },
  { name: '🇺🇸 USA (Los Angeles)', value: 'America/Los_Angeles' },
  { name: '🇨🇦 Canada (Vancouver)', value: 'America/Vancouver' },
  { name: '🇬🇧 United Kingdom', value: 'Europe/London' },
  { name: '🇵🇹 Portugal', value: 'Europe/Lisbon' },
  { name: '🇪🇸 Spain', value: 'Europe/Madrid' },
  { name: '🇫🇷 France', value: 'Europe/Paris' },
  { name: '🇩🇪 Germany', value: 'Europe/Berlin' },
  { name: '🇳🇱 Netherlands', value: 'Europe/Amsterdam' },
  { name: '🇧🇪 Belgium', value: 'Europe/Brussels' },
  { name: '🇸🇪 Sweden', value: 'Europe/Stockholm' },
  { name: '🇳🇴 Norway', value: 'Europe/Oslo' },
  { name: '🇷🇺 Russia (Moscow)', value: 'Europe/Moscow' },
  { name: '🇹🇷 Turkey', value: 'Europe/Istanbul' },
  { name: '🇮🇳 India', value: 'Asia/Kolkata' },
  { name: '🇨🇳 China', value: 'Asia/Shanghai' },
  { name: '🇯🇵 Japan', value: 'Asia/Tokyo' },
  { name: '🇰🇷 South Korea', value: 'Asia/Seoul' },
  { name: '🇮🇩 Indonesia', value: 'Asia/Jakarta' },
  { name: '🇦🇺 Australia (Sydney)', value: 'Australia/Sydney' },
  { name: '🇳🇿 New Zealand', value: 'Pacific/Auckland' },
  { name: '🇿🇦 South Africa', value: 'Africa/Johannesburg' },
  { name: '🇪🇬 Egypt', value: 'Africa/Cairo' },
  { name: '🇳🇬 Nigeria', value: 'Africa/Lagos' },
  { name: '🇸🇦 Saudi Arabia', value: 'Asia/Riyadh' },
  { name: '🇮🇷 Iran', value: 'Asia/Tehran' },
];

export const flagMap: Record<string, string> = {
  UTC: '🌍',
  'America/Sao_Paulo': '🇧🇷',
  'America/New_York': '🇺🇸',
  'America/Toronto': '🇨🇦',
  'Europe/Rome': '🇮🇹',
  'America/Argentina/Buenos_Aires': '🇦🇷',
  'America/Santiago': '🇨🇱',
  'America/Mexico_City': '🇲🇽',
  'America/Bogota': '🇨🇴',
  'America/Chicago': '🇺🇸',
  'America/Denver': '🇺🇸',
  'America/Los_Angeles': '🇺🇸',
  'America/Vancouver': '🇨🇦',
  'Europe/London': '🇬🇧',
  'Europe/Lisbon': '🇵🇹',
  'Europe/Madrid': '🇪🇸',
  'Europe/Paris': '🇫🇷',
  'Europe/Berlin': '🇩🇪',
  'Europe/Amsterdam': '🇳🇱',
  'Europe/Brussels': '🇧🇪',
  'Europe/Stockholm': '🇸🇪',
  'Europe/Oslo': '🇳🇴',
  'Europe/Moscow': '🇷🇺',
  'Europe/Istanbul': '🇹🇷',
  'Asia/Kolkata': '🇮🇳',
  'Asia/Shanghai': '🇨🇳',
  'Asia/Tokyo': '🇯🇵',
  'Asia/Seoul': '🇰🇷',
  'Asia/Jakarta': '🇮🇩',
  'Australia/Sydney': '🇦🇺',
  'Pacific/Auckland': '🇳🇿',
  'Africa/Johannesburg': '🇿🇦',
  'Africa/Cairo': '🇪🇬',
  'Africa/Lagos': '🇳🇬',
  'Asia/Riyadh': '🇸🇦',
  'Asia/Tehran': '🇮🇷',
};

export default [...timezones, ...genericTimezones];
